# name: secrets

# on: [push]

# jobs:
#   add-env:
#     name: Add Secret as Environment Variable
#     runs-on: ubuntu-latest
#     env:
#       GATSBY_GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
#     steps:
#       - name: Step One
#         uses: actions/checkout@v2
#       - name: Step Two
#         run: env | sort
