name: secrets

on: [push]

jobs:
  view:
    name: View Environment Variables
    runs-on: ubuntu-latest
    steps:
      - name: Step One
        uses: actions/checkout@v2
      - name: Step Two
        run: env | sort
