name: "secrets" # Name of your workflow

on:
  [push]
  # push:
  #   branches:
  #     - gatsby-dev # The trigger of the this workflow

jobs:
  build:
    runs-on: ubuntu-latest # Action uses Docker so only Linux is supported
    steps:
      - uses: actions/checkout@v1 # Checkout your triggered branch
        # - uses: xmflsct/action-publish-gatsby@v1 # Uses this action to run further steps
        with:
          # publishBranch: 'master' # Not required, default publishing branch is master
          GATSBY_GOOGLE_ANALYTICS_ID: ${{ secrets.GATSBY_GOOGLE_ANALYTICS_ID }}
          REACT_APP_GOOGLE_ANALYTICS_ID: ${{ secrets.REACT_APP_GOOGLE_ANALYTICS_ID }}
          GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
          # token: ${{ secrets.NAME }} # Your personal access token of GitHub, read more below of how to obtain one and keep it safe
          # name: 'your name' # Not required, default to action's maintainer
          # email: 'your@email.com' # Not required, default to action's maintainer
# name: secrets

# on: [push]

# jobs:
#   add-env:
#     name: Add Secret as Environment Variable
#     runs-on: ubuntu-latest
#     env:
#       GATSBY_GOOGLE_ANALYTICS_ID: ${{ secrets.GATSBY_GOOGLE_ANALYTICS_ID }}
#       REACT_APP_GOOGLE_ANALYTICS_ID: ${{ secrets.REACT_APP_GOOGLE_ANALYTICS_ID }}
#       GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
#     steps:
#       - name: Step One
#         uses: actions/checkout@v2
#       - name: Step Two
#         run: env | sort
