name: secrets

on: [push]

jobs:
  view-env:
    name: View Environment Variables
    runs-on: ubuntu-latest
    steps:
      - name: Step One
        uses: actions/checkout@v2
      - name: Step Two
        run: env | sort

  view-secret:
    name: View Secret Variables
    runs-on: ubuntu-latest
    steps:
      - name: Step One
        uses: actions/checkout@v2
        with:
          google-analytics-id: ${{ secrets.GOOGLE_ANALYTICS_ID }}
        env:
          google-analytics-id: ${{ secrets.GOOGLE_ANALYTICS_ID }}
      - name: Step Two
        run: secrets | sort
